from django.urls import path

from .views import (
    ActiveVisitorsView,
    BlacklistAuditView,
    BlacklistRemoveView,
    BlacklistView,
    ConfigHistoryView,
    ConfigView,
    DataOperationsView,
    DenyEntryView,
    EscortReleaseView,
    EscortsView,
    ExportDataView,
    ImportDataView,
    IssuePassView,
    LocationTrailView,
    ManualCheckView,
    OverstayView,
    RecentVisitsView,
    RecordEntryView,
    RecordExitView,
    RegisterVisitorView,
    ReportsView,
    ScanPassView,
    SecurityIncidentView,
    VerifyVisitorView,
    VIPActivityView,
    VIPListView,
    VIPProcessView,
    VisitingHoursView,
    VisitorHistoryView,
    VisitorIncidentHistoryView,
    ZonesView,
)

app_name = "vms"

urlpatterns = [
    path("register/", RegisterVisitorView.as_view(), name="register"),
    path("verify/", VerifyVisitorView.as_view(), name="verify"),
    path("pass/", IssuePassView.as_view(), name="issue-pass"),
    path("scan/", ScanPassView.as_view(), name="scan"),
    path("manual-check/", ManualCheckView.as_view(), name="manual-check"),
    path("entry/", RecordEntryView.as_view(), name="record-entry"),
    path("exit/", RecordExitView.as_view(), name="record-exit"),
    path("deny/", DenyEntryView.as_view(), name="deny-entry"),
    path("active/", ActiveVisitorsView.as_view(), name="active"),
    path("recent/", RecentVisitsView.as_view(), name="recent"),
    path("reports/", ReportsView.as_view(), name="reports"),
    path("blacklist/", BlacklistView.as_view(), name="blacklist"),
    path("blacklist/<int:entry_id>/remove/", BlacklistRemoveView.as_view(), name="blacklist-remove"),
    path("blacklist/audit/<str:id_number>/", BlacklistAuditView.as_view(), name="blacklist-audit"),
    path("history/<str:id_number>/", VisitorHistoryView.as_view(), name="history"),
    path("history/<str:id_number>/incidents/", VisitorIncidentHistoryView.as_view(), name="history-incidents"),
    path("location/<int:visit_id>/", LocationTrailView.as_view(), name="location"),
    path("overstay/", OverstayView.as_view(), name="overstay"),
    path("vip/process/", VIPProcessView.as_view(), name="vip-process"),
    path("vip/", VIPListView.as_view(), name="vip-list"),
    path("vip/<int:visit_id>/activity/", VIPActivityView.as_view(), name="vip-activity"),
    path("escorts/", EscortsView.as_view(), name="escorts"),
    path("escorts/<int:escort_id>/release/", EscortReleaseView.as_view(), name="escort-release"),
    path("config/", ConfigView.as_view(), name="config"),
    path("config/history/", ConfigHistoryView.as_view(), name="config-history"),
    path("visiting-hours/", VisitingHoursView.as_view(), name="visiting-hours"),
    path("zones/", ZonesView.as_view(), name="zones"),
    path("export/", ExportDataView.as_view(), name="export"),
    path("import/", ImportDataView.as_view(), name="import"),
    path("data-operations/", DataOperationsView.as_view(), name="data-operations"),
    path("incidents/", SecurityIncidentView.as_view(), name="incidents"),
]
