# Generated by Django 3.1.5 on 2025-08-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0004_auto_20250509_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleaccess',
            name='patent_management',
            field=models.BooleanField(default=False),
        ),
    ]
