# Generated by Django 3.1.5 on 2025-08-24 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0002_auto_20250822_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='submission_date',
            field=models.DateField(default=datetime.date(2025, 8, 24)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='interview_date',
            field=models.DateField(default=datetime.date(2025, 8, 24)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='submission_date',
            field=models.DateField(default=datetime.date(2025, 8, 24)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='test_date',
            field=models.DateField(default=datetime.date(2025, 8, 24)),
        ),
    ]
