# Generated by Django 5.2.6 on 2026-02-05 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0003_auto_20250824_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='submission_date',
            field=models.DateField(default=datetime.date(2026, 2, 5)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='interview_date',
            field=models.DateField(default=datetime.date(2026, 2, 5)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='submission_date',
            field=models.DateField(default=datetime.date(2026, 2, 5)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='test_date',
            field=models.DateField(default=datetime.date(2026, 2, 5)),
        ),
    ]
