# Generated by Django 5.2.6 on 2026-02-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0002_auto_20250402_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='year',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='course',
            name='pre_requisit_courses',
            field=models.ManyToManyField(blank=True, to='programme_curriculum.course'),
        ),
        migrations.AlterField(
            model_name='courseinstructor',
            name='year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='programme',
            name='programme_begin_year',
            field=models.PositiveIntegerField(default=2026),
        ),
    ]
