# Generated by Django 5.2.6 on 2026-02-05 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0006_student_hall_id'),
        ('academic_procedures', '0002_auto_20250402_1850'),
        ('globals', '0005_moduleaccess_patent_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantshipclaim',
            name='year',
            field=models.IntegerField(choices=[(2026, 2026), (2025, 2025)]),
        ),
        migrations.AlterField(
            model_name='course_registration',
            name='working_year',
            field=models.IntegerField(blank=True, choices=[(2026, 2026), (2025, 2025)], null=True),
        ),
        migrations.AlterField(
            model_name='finalregistrations',
            name='batch',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='messdue',
            name='year',
            field=models.IntegerField(choices=[(2026, 2026), (2025, 2025)]),
        ),
        migrations.AlterField(
            model_name='register',
            name='year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='teachingcreditregistration',
            name='approved_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_approved_course', to='academic_information.curriculum'),
        ),
        migrations.AlterField(
            model_name='teachingcreditregistration',
            name='curr_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_curr1', to='academic_information.curriculum'),
        ),
        migrations.AlterField(
            model_name='teachingcreditregistration',
            name='curr_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_curr2', to='academic_information.curriculum'),
        ),
        migrations.AlterField(
            model_name='teachingcreditregistration',
            name='curr_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_curr3', to='academic_information.curriculum'),
        ),
        migrations.AlterField(
            model_name='teachingcreditregistration',
            name='curr_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_curr4', to='academic_information.curriculum'),
        ),
        migrations.AlterField(
            model_name='teachingcreditregistration',
            name='supervisor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_supervisor_id', to='globals.faculty'),
        ),
        migrations.AlterField(
            model_name='thesistopicprocess',
            name='co_supervisor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_co_supervisor', to='globals.faculty'),
        ),
        migrations.AlterField(
            model_name='thesistopicprocess',
            name='member1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_member1', to='globals.faculty'),
        ),
        migrations.AlterField(
            model_name='thesistopicprocess',
            name='member2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_member2', to='globals.faculty'),
        ),
        migrations.AlterField(
            model_name='thesistopicprocess',
            name='member3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_member3', to='globals.faculty'),
        ),
        migrations.AlterField(
            model_name='thesistopicprocess',
            name='supervisor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_supervisor', to='globals.faculty'),
        ),
    ]
