# Generated by Django 3.1.5 on 2025-08-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0005_merge_20250421_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hall_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
