# Generated by Django 5.2.6 on 2026-02-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_auto_20250822_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previous_winner',
            name='year',
            field=models.IntegerField(default=2026),
        ),
    ]
